Count: 0
Reward: 10
Reward_When: 30
Previous: ""
Sequential: false
CreeperAwman:
  1 creeper:
  - creeper
  2 aw man:
  - aw man
  3 So we back in the mine:
  - So we back in the mine
  4 got our pickaxe swinging from:
  - got our pickaxe swinging from
  5 side to side:
  - side to side
  6 side side to side:
  - side side to side
  7 this task a grueling one:
  - this task a grueling one
  8 hope to find some diamonds:
  - hope to find some diamonds
  9 tonight:
  - tonight
  10 night:
  - night
  11 night:
  - night
  12 diamonds tonight:
  - diamonds tonight
  13 heads up:
  - heads up
  14 you hear sound:
  - you hear sound
  15 turn around and look up:
  - turn around and look up
  16 total shock fills your body:
  - total shock fills your body
  17 oh no its you again:
  - oh no its you again
  18 i can never forget those:
  - i can never forget those
  19 eyes:
  - eyes
  20 eyes:
  - eyes
  21 eyes:
  - eyes
  22 eyes eyes eyes:
  - eyes eyes eyes
  23 cause baby tonight:
  - cause baby tonight
  24 the creepers trying to steal all our stuff again:
  - the creepers trying to steal all our stuff again
  25 cause baby tonight:
  - cause baby tonight
  26 grab your pick shovel and bolt again:
  - grab your pick shovel and bolt again
  27 and run run until its done done:
  - and run run until its done done
  28 until the sun comes up in the morn:
  - until the sun comes up in the morn
  29 cause baby tonight:
  - cause baby tonight
  30 the creepers trying to steal all our stuff again:
  - the creepers trying to steal all our stuff again
